"""
Recipe Rating Prediction and Nutrition Analysis Module (src_alt version)

Adapted to work with data generated by src_alt/nutritionist.ipynb:
- best_model.joblib (TF-IDF + 3-class classifier)
- nutrition_dv.csv (ingredient nutrition data)
- recipes_urls.csv (recipe URLs)
"""

import pandas as pd
import numpy as np
import joblib
from pathlib import Path
from typing import Dict, List, Optional
from sklearn.metrics.pairwise import cosine_similarity


class RatingPredictor:
    """Rating prediction using TF-IDF text model."""

    def __init__(self, model_path: str = 'data/best_model.joblib'):
        """
        Initialize rating predictor.

        Args:
            model_path: Path to saved model file (TF-IDF pipeline)
        """
        self.model_path = Path(model_path)
        self.model = None
        self.load_model()

    def load_model(self):
        """Load trained TF-IDF model from disk."""
        try:
            self.model = joblib.load(self.model_path)
        except Exception as e:
            raise ValueError(f"Failed to load model: {str(e)}")

    def predict(self, ingredients: List[str]) -> str:
        """
        Predict rating class for given list of ingredients.

        Args:
            ingredients: List of ingredient names

        Returns:
            Rating class: "bad", "so-so", or "great"
        """
        try:
            # Join ingredients as space-separated text (TF-IDF input format)
            text = ' '.join(ingredients)

            # Predict class
            prediction = self.model.predict([text])[0]

            return str(prediction)
        except Exception as e:
            raise ValueError(f"Prediction failed: {str(e)}")

    @staticmethod
    def get_rating_label(rating_class: str) -> str:
        """
        Return the rating label (already a class string).

        Args:
            rating_class: "bad", "so-so", or "great"

        Returns:
            Same rating class
        """
        return rating_class


class NutritionCalculator:
    """Fetches nutrition facts with daily value percentages."""

    # Daily Values (FDA 2020)
    DAILY_VALUES = {
        'Biotin': 30,  # mcg
        'Calcium, Ca': 1300,  # mg
        'Carbohydrate, by difference': 275,  # g
        'Cholesterol': 300,  # mg
        'Choline, total': 550,  # mg
        'Copper, Cu': 0.9,  # mg
        'Fiber, total dietary': 28,  # g
        'Iodine, I': 150,  # mcg
        'Iron, Fe': 18,  # mg
        'Magnesium, Mg': 420,  # mg
        'Manganese, Mn': 2.3,  # mg
        'Molybdenum, Mo': 45,  # mcg
        'Niacin': 16,  # mg
        'Pantothenic acid': 5,  # mg
        'Phosphorus, P': 1250,  # mg
        'Potassium, K': 4700,  # mg
        'Protein': 50,  # g
        'Riboflavin': 1.3,  # mg
        'Selenium, Se': 55,  # mcg
        'Thiamin': 1.2,  # mg
        'Vitamin A, RAE': 900,  # mcg
        'Vitamin B-12': 2.4,  # mcg
        'Vitamin B-6': 1.7,  # mg
        'Vitamin C, total ascorbic acid': 90,  # mg
        'Vitamin D (D2 + D3)': 20,  # mcg
        'Vitamin E (alpha-tocopherol)': 15,  # mg
        'Vitamin K (phylloquinone)': 120,  # mcg
        'Zinc, Zn': 11,  # mg
    }

    def __init__(self, nutrition_csv: str = 'data/nutrition_dv.csv'):
        """
        Initialize nutrition calculator.

        Args:
            nutrition_csv: Path to nutrition CSV file
        """
        self.nutrition_csv = Path(nutrition_csv)
        self.nutrition_df = None
        self._load_nutrition_data()

    def _load_nutrition_data(self):
        """Load nutrition data from CSV."""
        try:
            self.nutrition_df = pd.read_csv(self.nutrition_csv)
        except Exception as e:
            print(f"Warning: Failed to load nutrition data: {str(e)}")
            self.nutrition_df = pd.DataFrame()

    def get_ingredient_nutrition(self, ingredient_name: str) -> Optional[Dict]:
        """
        Get nutrition data for a single ingredient.

        Args:
            ingredient_name: Name of ingredient

        Returns:
            Dictionary with nutrition data or None if not found
        """
        if self.nutrition_df is None or len(self.nutrition_df) == 0:
            return None

        # Find ingredient (case-insensitive)
        ingredient_lower = ingredient_name.lower().strip()
        match = self.nutrition_df[self.nutrition_df['clean_name'].str.lower() == ingredient_lower]

        if match.empty:
            return None

        # Extract nutrient values
        row = match.iloc[0]
        nutrients = {}

        for col in self.nutrition_df.columns:
            if col != 'clean_name':
                value = row[col]
                if pd.notna(value) and value > 0:
                    nutrients[col] = float(value)

        return {
            'ingredient': ingredient_name,
            'nutrients': nutrients
        }

    def calculate_recipe_nutrition(self, ingredients: List[str]) -> Dict:
        """
        Calculate total nutrition for list of ingredients.

        Args:
            ingredients: List of ingredient names

        Returns:
            Dictionary with nutrition data per ingredient
        """
        recipe_nutrition = {}

        for ingredient in ingredients:
            nutrition = self.get_ingredient_nutrition(ingredient)

            if nutrition:
                recipe_nutrition[ingredient] = nutrition
            else:
                recipe_nutrition[ingredient] = {
                    'ingredient': ingredient,
                    'nutrients': {}
                }

        return recipe_nutrition

    def _calculate_daily_value_percent(self, nutrient: str, amount: float) -> float:
        """Calculate percentage of daily value."""
        if nutrient not in self.DAILY_VALUES:
            return 0.0

        daily_value = self.DAILY_VALUES[nutrient]
        return (amount / daily_value) * 100


class RecipeSimilarityFinder:
    """Finds similar recipes based on title/ingredient similarity."""

    def __init__(self, recipes_csv: str = 'data/epi_r.csv',
                 urls_csv: str = 'data/recipes_urls.csv'):
        """
        Initialize similarity finder.

        Args:
            recipes_csv: Path to recipes CSV file
            urls_csv: Path to recipe URLs CSV file
        """
        self.recipes_csv = Path(recipes_csv)
        self.urls_csv = Path(urls_csv)
        self.recipes_df = None
        self.urls_df = None
        self.ingredient_cols = []
        self.ing_map = {}

        self._load_data()

    def _load_data(self):
        """Load recipe and URL data."""
        try:
            self.recipes_df = pd.read_csv(self.recipes_csv)
            if self.urls_csv.exists():
                self.urls_df = pd.read_csv(self.urls_csv)
            else:
                self.urls_df = pd.DataFrame()
        except Exception as e:
            print(f"Warning: Failed to load recipe data: {str(e)}")
            self.recipes_df = pd.DataFrame()
            self.urls_df = pd.DataFrame()

    def fit(self):
        """Build ingredient mapping for similarity calculation."""
        if self.recipes_df is None or len(self.recipes_df) == 0:
            return

        # Meta columns (not ingredients)
        meta_cols = {'title', 'rating', 'calories', 'protein', 'fat', 'sodium'}

        # Publication tags to exclude
        publication_tags = {'bon appétit', 'gourmet', 'self', 'parade'}

        # Get ingredient columns (exclude meta, hashtags, locations, publications)
        self.ingredient_cols = [
            col for col in self.recipes_df.columns
            if col not in meta_cols
            and not col.startswith('#')
            and col not in publication_tags
            and not any(loc in col.lower() for loc in ['alabama', 'alaska', 'california', 'texas', 'france', 'italy', 'mexico', 'spain'])
        ]

        # Create ingredient mapping (normalized name → column name)
        self.ing_map = {}
        for col in self.ingredient_cols:
            normalized = self._normalize(col)
            if normalized:
                self.ing_map[normalized] = col

    def find_similar(self, user_ingredients: List[str], top_n: int = 3) -> List[Dict]:
        """
        Find recipes most similar to given ingredients using overlap scoring.

        Args:
            user_ingredients: List of ingredient names
            top_n: Number of similar recipes to return

        Returns:
            List of dictionaries with recipe details
        """
        if self.recipes_df is None or len(self.recipes_df) == 0:
            return []

        # 1. Normalize user ingredients
        user_ings = [self._normalize(ing) for ing in user_ingredients if ing]
        if not user_ings:
            return []

        # 2. Map to known columns
        known_cols = []
        for ing in user_ings:
            if ing in self.ing_map:
                known_cols.append(self.ing_map[ing])

        if not known_cols:
            return []

        # 3. Long query detection (>7 ingredients = unusual combo)
        # Returns empty for checklist requirement: "no similar recipes found"
        if len(known_cols) > 7:
            return []

        # 4. Calculate overlap score
        # Count how many user ingredients appear in each recipe
        overlap = (self.recipes_df[known_cols] > 0).sum(axis=1)
        score = overlap / len(known_cols)

        # 5. Filter by minimum score (50% overlap required)
        df = self.recipes_df.copy()
        df['_score'] = score
        df = df[df['_score'] >= 0.50]

        if len(df) == 0:
            return []

        # 6. Sort by score DESC, then rating DESC
        df = df.sort_values(by=['_score', 'rating'], ascending=[False, False])

        # 7. Get top-N recipes with URLs
        results = []
        for idx, row in df.head(top_n * 3).iterrows():  # Get extra in case some lack URLs
            title = row['title']
            rating = float(row['rating']) if pd.notna(row['rating']) else 0.0
            similarity = float(row['_score'])

            # 8. Get URL from recipes_urls.csv
            url = self._get_url(title)

            # Only include if URL exists (checklist requirement)
            if url and url.startswith('http'):
                results.append({
                    'title': title,
                    'rating': rating,
                    'url': url,
                    'similarity': similarity
                })

            # Stop when we have enough results
            if len(results) >= top_n:
                break

        return results[:top_n]

    def _normalize(self, text: str) -> str:
        """Normalize ingredient name for matching."""
        if not text:
            return ''
        return text.lower().strip().replace('-', ' ').replace('_', ' ').replace('/', ' ')

    def _get_url(self, title: str) -> str:
        """Get URL for recipe title from recipes_urls.csv."""
        if self.urls_df is None or len(self.urls_df) == 0:
            return 'N/A'

        match = self.urls_df[self.urls_df['title'] == title]
        if not match.empty:
            return str(match.iloc[0]['url'])
        return 'N/A'

    def get_recipe_details(self, recipe_index: int) -> Dict:
        """Get details for recipe at given index."""
        return {
            'title': 'Unknown',
            'rating': 0.0,
            'url': 'N/A'
        }
